### ISSUE TITLE
coinmarketcap bitcoin 2018-01-01 2018-01-30 not work anymore.

### ISSUE THREAD

**Issue by CyberFork** [Waultics/coinmarketcap-history#30]
coinmarketcap bitcoin 2018-01-01 2018-01-30
100%|█████████████████████████████████████████
100%|█████████████████████████████████████████
███████████| 1/1 [00:33<00:00, 33.75s/it]
Traceback (most recent call last):
  File "c:\users\i6\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\i6\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\i6\AppData\Local\Programs\Python\Python37\Scripts\coinmarketcap.exe\__main__.py", line 7, in <module>
  File "c:\users\i6\appdata\local\programs\python\python37\lib\site-packages\cmc\coinmarketcap.py", line 101, in main
    df = getDataFor(cryptocurrencies, start_date, end_date, asynchro = asynchro)
  File "c:\users\i6\appdata\local\programs\python\python37\lib\site-packages\cmc\coinmarketcap.py", line 60, in getDataFor
    df = utils.processDataFrame(temp_df)
  File "c:\users\i6\appdata\local\programs\python\python37\lib\site-packages\cmc\utils\utils.py", line 137, in processDataFrame
    cols.remove('Date')
ValueError: list.remove(x): x not in list

**Comment by zhiyuan8** [comment]
same issue
